### ISSUE TITLE
前端响应速度很慢，演示地址和自行搭建的如此

### ISSUE THREAD

**Issue by myleo1** [ThingsPanel/ThingsPanel-Backend-Vue#1]
在刷新页面或者进入页面的时候很慢，但是进入之后操作不慢

**Comment by myleo1** [comment]
![image](https://user-images.githubusercontent.com/66349676/154192001-11e0b01e-0b40-4036-9506-d2150456bb4e.png)
原因是因为图中的资源被墙，导致国内无法访问

**Comment by hezhuozhuo** [comment]
这个问题已处理
